name: MLops CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     pytest tests/

      # - name: Lint code
      #   run: |
      #     flake8 .

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     push: true
      #     tags: user/house-price-predictor:latest
      #     # Uncomment and set up secrets for pushing to Docker Hub or other registries
          # secrets:
          #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          #   DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}